### ISSUE TITLE
can gulp-rev-replace replace in jade?

### ISSUE THREAD

**Issue by YDSS** [jamesknelson/gulp-rev-replace#48]
Hi, I'm using `gulp-rev-replace` for a while and it's fine, until I decide replace "plain html" with template. I found gulp-rev-replace can not replace path in jade, then I read doc and issues and got nothing useful. Does anyone has some advices?

**Comment by futuranna** [comment]
You can add jade to the **replaceInExtensions**
```
gulp.src('src/**/*.jade')
        .pipe(revReplace({
            replaceInExtensions: ['.jade']
        }))
        .pipe(gulp.dest('dist'));
```

**Comment by adouglas** [comment]
The above fix is correct, and this should be closed as not a bug
